# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAyLaCZ39Qht8A8Y6Pq3BHZzfJ7x4jt4
"""

# student result programm
student_name = input(" enter student name :")
num_subject = int(input("enter number of subject :"))
total_marks = 0
subject = []
marks_list = []
# applying for loop for takeing subject name and marks
for i in range (1, num_subject + 1):
  subject_name = input(f"enter name of subject   {i} : ")
  marks = float(input(f"enter marks of {subject_name}"))
  subject.append(subject_name)
  marks_list.append(marks)
  total_marks += marks
# calculating average of subject
average_marks = total_marks/num_subject
# calculating percentage
percentage = (total_marks /(num_subject * 100))* 100
# check pass or fail
if percentage >= 50 :
  result = "Pass"
  # nested if for guide calculation
  if percentage >80:
    grade = "A+"
  elif percentage >= 70:
    grade ="A"
  elif percentage >=60 :
    grade = "B"
  elif percentage >= 50 :
    grade = "c"
  else:
    grade ="D"
else:
  result = "fail"
  grade = "F"

# prenting final report
print("\n=========STUDENT REPORT===========")
print(f"student name : {student_name}")
print("\nh subjects and marks :")
for i in range(num_subject):
 print(f"subject{i} : {marks_list[i]}")

print("\n total marks :", total_marks)
print("\n Average marks :", average_marks)
print("\n percentage", percentage,"%")
print("\n result :", result)
print("\n grade :", grade)
print("------------------------------------------------")



